Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Failed to fetch data: 403
Fetching store data...
Traceback (most recent call last):
  File "/app/main.py", line 20, in <module>
    fetch_store_data()
  File "/app/main.py", line 13, in fetch_store_data
    response = requests.get(f"{directus_api_url}/items/stores", headers=headers)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/items/stores': No scheme supplied. Perhaps you meant https://None/items/stores?
Directus API URL: None
Directus API Token: None
Fetching store data...
Traceback (most recent call last):
  File "/app/main.py", line 22, in <module>
    fetch_store_data()
  File "/app/main.py", line 15, in fetch_store_data
    response = requests.get(f"{directus_api_url}/items/stores", headers=headers)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/items/stores': No scheme supplied. Perhaps you meant https://None/items/stores?
Directus API URL: None
Directus API Token: None
Fetching store data...
Traceback (most recent call last):
  File "/app/main.py", line 22, in <module>
    fetch_store_data()
  File "/app/main.py", line 15, in fetch_store_data
    response = requests.get(f"{directus_api_url}/items/stores", headers=headers)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/items/stores': No scheme supplied. Perhaps you meant https://None/items/stores?
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from pydirectus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/__init__.py", line 1, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.9/site-packages/pydirectus/directus.py", line 5, in <module>
    from .query import Query
  File "/usr/local/lib/python3.9/site-packages/pydirectus/query.py", line 14, in <module>
    from .field import Field
  File "/usr/local/lib/python3.9/site-packages/pydirectus/field.py", line 1, in <module>
    from .typing import Alias, Other, Csv, Hash, Uuid, Json, Union, List
  File "/usr/local/lib/python3.9/site-packages/pydirectus/typing.py", line 1, in <module>
    from typing import TypeAlias, List, Any, Union, Dict, Optional
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    from py_directus import Directus
  File "/usr/local/lib/python3.12/site-packages/py_directus/__init__.py", line 9, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.12/site-packages/py_directus/directus.py", line 14, in <module>
    import magic
  File "/usr/local/lib/python3.12/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    from py_directus import Directus
  File "/usr/local/lib/python3.12/site-packages/py_directus/__init__.py", line 9, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.12/site-packages/py_directus/directus.py", line 14, in <module>
    import magic
  File "/usr/local/lib/python3.12/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    from py_directus import Directus
  File "/usr/local/lib/python3.12/site-packages/py_directus/__init__.py", line 9, in <module>
    from .directus import Directus
  File "/usr/local/lib/python3.12/site-packages/py_directus/directus.py", line 14, in <module>
    import magic
  File "/usr/local/lib/python3.12/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: http://directus:8055
Directus API Token: hxbQOJyLffUqoDIzsbWnth8E1hvRTBWu
Data fetched: [{'id': 8, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-10-27T23:08:18.000Z', 'user_updated': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_updated': '2024-12-01T00:10:42.000Z', 'name': 'Decovetro - Trendyol', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'decovetro', 'api_connect_info': None, 'import_status': 'product_info_not_fetched', 'products': [973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072]}, {'id': 73, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:39:02.000Z', 'user_updated': None, 'date_updated': None, 'name': 'asdaasdfasdf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}, {'id': 74, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:47:45.000Z', 'user_updated': None, 'date_updated': None, 'name': 'sadfasdf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}, {'id': 75, 'status': 'draft', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:49:50.000Z', 'user_updated': None, 'date_updated': None, 'name': 'adfadsfdsaf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}]
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: http://directus:8055
Directus API Token: hxbQOJyLffUqoDIzsbWnth8E1hvRTBWu
Data fetched: [{'id': 8, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-10-27T23:08:18.000Z', 'user_updated': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_updated': '2024-12-01T00:10:42.000Z', 'name': 'Decovetro - Trendyol', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'decovetro', 'api_connect_info': None, 'import_status': 'product_info_not_fetched', 'products': [973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072]}, {'id': 73, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:39:02.000Z', 'user_updated': None, 'date_updated': None, 'name': 'asdaasdfasdf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}, {'id': 74, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:47:45.000Z', 'user_updated': None, 'date_updated': None, 'name': 'sadfasdf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}, {'id': 75, 'status': 'draft', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:49:50.000Z', 'user_updated': None, 'date_updated': None, 'name': 'adfadsfdsaf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}]
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Directus API URL: None
Directus API Token: None
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Data fetched: [{'id': 8, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-10-27T23:08:18.000Z', 'user_updated': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_updated': '2024-12-01T00:10:42.000Z', 'name': 'Decovetro - Trendyol', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'decovetro', 'api_connect_info': None, 'import_status': 'product_info_not_fetched', 'products': [973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072]}, {'id': 73, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:39:02.000Z', 'user_updated': None, 'date_updated': None, 'name': 'asdaasdfasdf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}, {'id': 74, 'status': 'published', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:47:45.000Z', 'user_updated': None, 'date_updated': None, 'name': 'sadfasdf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}, {'id': 75, 'status': 'draft', 'user_created': '778150e4-1260-46b7-87a0-5c16998b63b5', 'date_created': '2024-11-28T10:49:50.000Z', 'user_updated': None, 'date_updated': None, 'name': 'adfadsfdsaf', 'user': 'cf32c9bf-212e-48d5-8f34-307c671f5782', 'store_type': 'trendyol', 'api_connect_info': {'api_key': 'GpuS1j4P3psPZw0UtrOM', 'store_id': '1005260', 'token_key': 'R3B1UzFqNFAzcHNQWncwVXRyT006MjQ1QlM4SWdsb0plcUk0UW1ENFk=', 'api_secret': '245BS8IgloJeqI4QmD4Y'}, 'import_status': 'product_info_not_fetched', 'products': []}]
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
/usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "schema" in "BaseDirectusRelation" shadows an attribute in parent "DirectusModel"
  warnings.warn(
Environment variables for Directus API URL or Token are not set.
